<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\LogicException;
use Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Component\DependencyInjection\ParameterBag\FrozenParameterBag;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class CachedContainer extends Container
{
    protected $parameters = [];

    public function __construct()
    {
        $this->parameters = $this->getDefaultParameters();

        $this->services = $this->privates = [];
        $this->syntheticIds = [
            'routes' => true,
        ];
        $this->methodMap = [
            'App\\User\\Representation\\Controller\\GetUserController' => 'getGetUserControllerService',
            'App\\User\\Representation\\Controller\\UserRegisterController' => 'getUserRegisterControllerService',
            'framework' => 'getFrameworkService',
        ];

        $this->aliases = [];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return [
            'App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommand' => true,
            'App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommandHandler' => true,
            'App\\User\\Application\\Query\\GetUser\\GetUserQuery' => true,
            'App\\User\\Application\\Query\\GetUser\\GetUserQueryHandler' => true,
            'App\\User\\Application\\Query\\GetUser\\GetUserResponse' => true,
            'App\\User\\Representation\\View' => true,
            'Fortizan\\Tekton\\Attribute\\ApiController' => true,
            'Fortizan\\Tekton\\Bus\\Command\\Attribute\\CommandHandler' => true,
            'Fortizan\\Tekton\\Bus\\Command\\CommandBus' => true,
            'Fortizan\\Tekton\\Bus\\Command\\Contract\\CommandInterface' => true,
            'Fortizan\\Tekton\\Bus\\Query\\Attribute\\QueryHandler' => true,
            'Fortizan\\Tekton\\Bus\\Query\\Contract\\QueryInterface' => true,
            'Fortizan\\Tekton\\Bus\\Query\\QueryBus' => true,
            'Fortizan\\Tekton\\Container\\Container' => true,
            'Fortizan\\Tekton\\Controller\\ErrorController' => true,
            'Fortizan\\Tekton\\DependencyInjection\\Compiler\\Cqrs\\CommandHandlerPass' => true,
            'Fortizan\\Tekton\\DependencyInjection\\Compiler\\Cqrs\\QueryHandlerPass' => true,
            'Fortizan\\Tekton\\EventListener\\ContentLengthListener' => true,
            'Fortizan\\Tekton\\EventListener\\GoogleListener' => true,
            'Fortizan\\Tekton\\EventListener\\StringResponseListener' => true,
            'Fortizan\\Tekton\\Http\\Event\\ResponseEvent' => true,
            'Fortizan\\Tekton\\Http\\Event\\TestEvent' => true,
            'Fortizan\\Tekton\\Http\\Kernal' => true,
            'Fortizan\\Tekton\\Routing\\RouteAttributeClassLoader' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface $commandBus' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface $messageBus' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface $queryBus' => true,
            'argument_resolver' => true,
            'context' => true,
            'controller_resolver' => true,
            'dispatcher' => true,
            'listener.exception' => true,
            'listener.google' => true,
            'listener.response' => true,
            'listener.router' => true,
            'listener.string_response_listener' => true,
            'matcher' => true,
            'messenger.bus.default' => true,
            'messenger.bus.default.messenger.handlers_locator' => true,
            'messenger.middleware.handle_message' => true,
            'request_stack' => true,
            'tekton.bus.command' => true,
            'tekton.bus.command.locator' => true,
            'tekton.bus.command.messenger.handlers_locator' => true,
            'tekton.bus.command.middleware' => true,
            'tekton.bus.query' => true,
            'tekton.bus.query.locator' => true,
            'tekton.bus.query.messenger.handlers_locator' => true,
            'tekton.bus.query.middleware' => true,
        ];
    }

    /**
     * Gets the public 'App\User\Representation\Controller\GetUserController' shared autowired service.
     *
     * @return \App\User\Representation\Controller\GetUserController
     */
    protected static function getGetUserControllerService($container)
    {
        return $container->services['App\\User\\Representation\\Controller\\GetUserController'] = new \App\User\Representation\Controller\GetUserController(new \Fortizan\Tekton\Bus\Query\QueryBus(new \Symfony\Component\Messenger\MessageBus([new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\User\\Application\\Query\\GetUser\\GetUserQuery' => [new \App\User\Application\Query\GetUser\GetUserQueryHandler()]]))])));
    }

    /**
     * Gets the public 'App\User\Representation\Controller\UserRegisterController' shared autowired service.
     *
     * @return \App\User\Representation\Controller\UserRegisterController
     */
    protected static function getUserRegisterControllerService($container)
    {
        return $container->services['App\\User\\Representation\\Controller\\UserRegisterController'] = new \App\User\Representation\Controller\UserRegisterController(new \Fortizan\Tekton\Bus\Command\CommandBus(new \Symfony\Component\Messenger\MessageBus([new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommand' => [new \App\User\Application\Command\RegisterUser\RegisterUserCommandHandler()]]))])));
    }

    /**
     * Gets the public 'framework' shared service.
     *
     * @return \Fortizan\Tekton\Http\Kernal
     */
    protected static function getFrameworkService($container)
    {
        $a = new \Symfony\Component\EventDispatcher\EventDispatcher();

        $b = new \Symfony\Component\HttpFoundation\RequestStack();

        $a->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\RouterListener(new \Symfony\Component\Routing\Matcher\UrlMatcher(($container->services['routes'] ?? $container->get('routes', 1)), new \Symfony\Component\Routing\RequestContext()), $b));
        $a->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\ResponseListener('ISO-8859-1'));
        $a->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\ErrorListener('Fortizan\\Tekton\\Controller\\ErrorController::handle'));
        $a->addSubscriber(new \Fortizan\Tekton\EventListener\GoogleListener());
        $a->addSubscriber(new \Fortizan\Tekton\EventListener\StringResponseListener());

        return $container->services['framework'] = new \Fortizan\Tekton\Http\Kernal($a, new \Symfony\Component\HttpKernel\Controller\ContainerControllerResolver($container), $b, new \Symfony\Component\HttpKernel\Controller\ArgumentResolver());
    }

    public function getParameter(string $name): array|bool|string|int|float|\UnitEnum|null
    {
        if (!(isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters))) {
            throw new ParameterNotFoundException($name);
        }

        if (isset($this->loadedDynamicParameters[$name])) {
            $value = $this->loadedDynamicParameters[$name] ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
        } else {
            $value = $this->parameters[$name];
        }

        return $value;
    }

    public function hasParameter(string $name): bool
    {
        return isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters);
    }

    public function setParameter(string $name, $value): void
    {
        throw new LogicException('Impossible to call set() on a frozen ParameterBag.');
    }

    public function getParameterBag(): ParameterBagInterface
    {
        if (!isset($this->parameterBag)) {
            $parameters = $this->parameters;
            foreach ($this->loadedDynamicParameters as $name => $loaded) {
                $parameters[$name] = $loaded ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
            }
            $this->parameterBag = new FrozenParameterBag($parameters, []);
        }

        return $this->parameterBag;
    }

    private $loadedDynamicParameters = [];
    private $dynamicParameters = [];

    private function getDynamicParameter(string $name)
    {
        throw new ParameterNotFoundException($name);
    }

    protected function getDefaultParameters(): array
    {
        return [
            'kernel.project_dir' => '/home/celestis/Documents/learning/tekton/packages/Tekton/src/Container/../../../../src',
            'charset' => 'ISO-8859-1',
        ];
    }
}
