<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\LogicException;
use Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Component\DependencyInjection\ParameterBag\FrozenParameterBag;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class CachedContainer extends Container
{
    protected $parameters = [];

    public function __construct()
    {
        $this->parameters = $this->getDefaultParameters();

        $this->services = $this->privates = [];
        $this->syntheticIds = [
            'routes' => true,
        ];
        $this->methodMap = [
            'App\\Context\\Representation\\Controller\\LeapYearController' => 'getLeapYearControllerService',
            'App\\Context\\Representation\\Controller\\TestController' => 'getTestControllerService',
            'App\\User\\Representation\\Controller\\UserRegisterController' => 'getUserRegisterControllerService',
            'framework' => 'getFrameworkService',
        ];

        $this->aliases = [];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return [
            'App\\Context\\Application\\Command\\UserMessage' => true,
            'App\\Context\\Application\\Command\\UserMessageHandler' => true,
            'App\\Context\\Domain\\Entity\\LeapYear' => true,
            'App\\Context\\Representation\\View' => true,
            'App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommand' => true,
            'App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommandHandler' => true,
            'Fortizan\\Tekton\\Attribute\\Cqrs\\AsCommandHandler' => true,
            'Fortizan\\Tekton\\Container\\Container' => true,
            'Fortizan\\Tekton\\Controller\\ErrorController' => true,
            'Fortizan\\Tekton\\Database\\AsQueryHandler' => true,
            'Fortizan\\Tekton\\DependencyInjection\\Compiler\\Cqrs\\CommandHandlerPass' => true,
            'Fortizan\\Tekton\\EventListener\\ContentLengthListener' => true,
            'Fortizan\\Tekton\\EventListener\\GoogleListener' => true,
            'Fortizan\\Tekton\\EventListener\\StringResponseListener' => true,
            'Fortizan\\Tekton\\Event\\ResponseEvent' => true,
            'Fortizan\\Tekton\\Event\\TestEvent' => true,
            'Fortizan\\Tekton\\Http\\Kernal' => true,
            'Fortizan\\Tekton\\Interface\\CommandHandlerInterface' => true,
            'Fortizan\\Tekton\\Interface\\CommandInterface' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface $commandBus' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface $messageBus' => true,
            'argument_resolver' => true,
            'context' => true,
            'controller_resolver' => true,
            'dispatcher' => true,
            'listener.exception' => true,
            'listener.google' => true,
            'listener.response' => true,
            'listener.router' => true,
            'listener.string_response_listener' => true,
            'matcher' => true,
            'messenger.bus.default' => true,
            'messenger.bus.default.messenger.handlers_locator' => true,
            'messenger.middleware.handle_message' => true,
            'request_stack' => true,
            'tekton.bus.command' => true,
            'tekton.bus.command.locator' => true,
            'tekton.bus.command.messenger.handlers_locator' => true,
            'tekton.bus.command.middleware' => true,
        ];
    }

    /**
     * Gets the public 'App\Context\Representation\Controller\LeapYearController' shared autowired service.
     *
     * @return \App\Context\Representation\Controller\LeapYearController
     */
    protected static function getLeapYearControllerService($container)
    {
        return $container->services['App\\Context\\Representation\\Controller\\LeapYearController'] = new \App\Context\Representation\Controller\LeapYearController();
    }

    /**
     * Gets the public 'App\Context\Representation\Controller\TestController' shared autowired service.
     *
     * @return \App\Context\Representation\Controller\TestController
     */
    protected static function getTestControllerService($container)
    {
        return $container->services['App\\Context\\Representation\\Controller\\TestController'] = new \App\Context\Representation\Controller\TestController(new \Symfony\Component\Messenger\MessageBus([new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\Context\\Application\\Command\\UserMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.vcRN_Hf'] ?? self::get_Messenger_HandlerDescriptor_VcRNHfService($container));
        }, 1)]))]));
    }

    /**
     * Gets the public 'App\User\Representation\Controller\UserRegisterController' shared autowired service.
     *
     * @return \App\User\Representation\Controller\UserRegisterController
     */
    protected static function getUserRegisterControllerService($container)
    {
        return $container->services['App\\User\\Representation\\Controller\\UserRegisterController'] = new \App\User\Representation\Controller\UserRegisterController(new \Symfony\Component\Messenger\MessageBus([new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommand' => [new \App\User\Application\Command\RegisterUser\RegisterUserCommandHandler()]]))]));
    }

    /**
     * Gets the public 'framework' shared service.
     *
     * @return \Fortizan\Tekton\Http\Kernal
     */
    protected static function getFrameworkService($container)
    {
        $a = new \Symfony\Component\EventDispatcher\EventDispatcher();

        $b = new \Symfony\Component\HttpFoundation\RequestStack();

        $a->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\RouterListener(new \Symfony\Component\Routing\Matcher\UrlMatcher(($container->services['routes'] ?? $container->get('routes', 1)), new \Symfony\Component\Routing\RequestContext()), $b));
        $a->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\ResponseListener('ISO-8859-1'));
        $a->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\ErrorListener('Fortizan\\Tekton\\Controller\\ErrorController::handle'));
        $a->addSubscriber(new \Fortizan\Tekton\EventListener\GoogleListener());
        $a->addSubscriber(new \Fortizan\Tekton\EventListener\StringResponseListener());

        return $container->services['framework'] = new \Fortizan\Tekton\Http\Kernal($a, new \Symfony\Component\HttpKernel\Controller\ContainerControllerResolver($container), $b, new \Symfony\Component\HttpKernel\Controller\ArgumentResolver());
    }

    /**
     * Gets the private '.messenger.handler_descriptor.vcRN_Hf' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    protected static function get_Messenger_HandlerDescriptor_VcRNHfService($container)
    {
        return $container->privates['.messenger.handler_descriptor.vcRN_Hf'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Context\Application\Command\UserMessageHandler(), []);
    }

    public function getParameter(string $name): array|bool|string|int|float|\UnitEnum|null
    {
        if (!(isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters))) {
            throw new ParameterNotFoundException($name);
        }

        if (isset($this->loadedDynamicParameters[$name])) {
            $value = $this->loadedDynamicParameters[$name] ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
        } else {
            $value = $this->parameters[$name];
        }

        return $value;
    }

    public function hasParameter(string $name): bool
    {
        return isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters);
    }

    public function setParameter(string $name, $value): void
    {
        throw new LogicException('Impossible to call set() on a frozen ParameterBag.');
    }

    public function getParameterBag(): ParameterBagInterface
    {
        if (!isset($this->parameterBag)) {
            $parameters = $this->parameters;
            foreach ($this->loadedDynamicParameters as $name => $loaded) {
                $parameters[$name] = $loaded ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
            }
            $this->parameterBag = new FrozenParameterBag($parameters, []);
        }

        return $this->parameterBag;
    }

    private $loadedDynamicParameters = [];
    private $dynamicParameters = [];

    private function getDynamicParameter(string $name)
    {
        throw new ParameterNotFoundException($name);
    }

    protected function getDefaultParameters(): array
    {
        return [
            'charset' => 'ISO-8859-1',
        ];
    }
}
